import type { Metadata } from "next";
import localFont from "next/font/local";
import TranslationsProvider from "@/utils/TranslationsProvider";
import initTranslations from "../i18n";
import "../../styles/globals.scss";

export const metadata: Metadata = {
  title: "SCI HIBISCUS - Chaque Africain Sous un Toit",
  description: "Generated by create next app",
};

const regular = localFont({
  src: "../fonts/HelveticaNowDisplay-Regular.ttf",
  variable: "--regular-font",
});

const medium = localFont({
  src: "../fonts/HelveticaNowDisplay-Medium.ttf",
  variable: "--medium-font",
});

const bold = localFont({
  src: "../fonts/HelveticaNowDisplay-Bold.ttf",
  variable: "--bold-font",
});

type Props = {
  params: Promise<{ locale: string }>;
};

/**Translations */
const i18nNamespaces = ["Navigation", "HomePage", "Projects"];

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  // ① Await the promise:
  const { locale } = await params;

  const { resources } = await initTranslations(locale, i18nNamespaces);
  return (
    <html lang={locale}>
      <body
        className={`${regular.variable} ${medium.variable} ${bold.variable}`}
      >
        <TranslationsProvider
          resources={resources}
          locale={locale}
          namespaces={i18nNamespaces}
        >
          {children}
        </TranslationsProvider>
      </body>
    </html>
  );
}
