import type { Metadata } from "next";
import localFont from "next/font/local";
import TranslationsProvider from "@/utils/TranslationsProvider";
import initTranslations from "../i18n";
import "../../styles/globals.scss";


export const metadata: Metadata = {
  title: "SCI HIBISCUS - Chaque Africain Sous un Toit",
  description: "Generated by create next app",
};

const regular = localFont({
  src: "../fonts/HelveticaNowDisplay-Regular.ttf",
  variable: "--regular-font",
});

const medium = localFont({
  src: "../fonts/HelveticaNowDisplay-Medium.ttf",
  variable: "--medium-font",
});

const bold = localFont({
  src: "../fonts/HelveticaNowDisplay-Bold.ttf",
  variable: "--bold-font",
});


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${regular.variable} ${medium.variable} ${bold.variable}`}>
        {children}
      </body>
    </html>
  );
}
