import type { Metadata } from "next";
import initTranslations from "../../i18n";
import "../../styles/globals.scss";

export const metadata: Metadata = {
  title: "SCI HIBISCUS - Chaque Africain Sous un Toit",
  description: "Generated by create next app",
};

type Props = {
  params: Promise<{ locale: string }>;
};

/**Translations */
const i18nNamespaces = ["Navigation", "HomePage"];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
