import type { Metadata } from "next";
import initTranslations from "../../i18n";

export const metadata: Metadata = {
  title: "Buy Land - Sci Hibiscus",
  description: "Generated by create next app",
};

type Props = {
  params: Promise<{ locale: string }>;
};

/**Translations */
const i18nNamespaces = ["Navigation", "HomePage", "ProjectsPage", "BuylandPage"];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
